models:
  - model: mistralai/Mistral-7B-v0.1
  - model: mistralai/Mistral-7B-Instruct-v0.1
    parameters:
      density: 0.5
      weight: 0.5
  - model: DeepMount00/Mistral-Ita-7b
    parameters:
      density: 0.5
      weight: 0.25
  - model: timpal0l/Mistral-7B-v0.1-flashback-v2
    parameters:
      density: 0.5
      weight: 0.25
merge_method: ties
base_model: mistralai/Mistral-7B-v0.1
parameters:
  normalize: true
dtype: float16
